export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as ProductList } from './ProductList/ProductList'
export { default as Button } from './Button/Button'
export { default as Loader } from './Loader/Loader'
export { default as ComingSoon } from './ComingSoon/ComingSoon'
export { default as Product } from './Product/Product'
export { default as Error } from './Error/Error'
